# Generated by Django 6.1 on 2026-09-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('text', models.TextField()),
                ('pub_date', models.DateField(auto_now_add=True, help_text='date published')),
                ('startups', models.ManyToManyField(related_name='blog_posts', to='organizer.startup')),
                ('tags', models.ManyToManyField(related_name='blog_posts', to='organizer.tag')),
            ],
            options={
                'verbose_name': 'blog post',
                'ordering': ['-pub_date', 'title'],
                'get_latest_by': 'pub_date',
            },
        ),
    ]
